CREATE VIEW dbo.VW_RPTINV_ASPURJAB AS
SELECT
	(
	SELECT
		COUNT(st.TAHUN) AS JMLPST
	FROM
		tl_individu_standard st
	WHERE
		st.POLICYNO = tl.POLICYNO
		AND st.BULAN = tl.TEMP_BULAN
		AND st.TAHUN = tl.TEMP_TAHUN
		AND st.ID_CHILD = tl.ID_CHILD
		AND st.IDDIVISION = tl.IDDIVISION
		AND st.IDSUB = tl.IDSUB
		AND st.STATUS = 1) AS JMLPESERTA_PERDIVISI,
	(
	SELECT
		COUNT(non.TAHUN) AS COUNTED
	FROM
		tl_individu_standard non
	WHERE
		non.POLICYNO = tl.POLICYNO
		AND non.BULAN = tl.TEMP_BULAN
		AND non.TAHUN = tl.TEMP_TAHUN
		AND non.ID_CHILD = tl.ID_CHILD
		AND non.STATUS = 1) AS JMLPESERTA_PUSAT,
	tl.*
from
	tl_invoice_standard tl
WHERE
	ID_CHILD = 27
	AND NOINVOICE IS NOT NULL
	AND KOTA IS NOT NULL
