CREATE VIEW dbo.VW_RPTINV_NONASPURJAB AS
SELECT
	(
	SELECT
		COUNT(st.TAHUN) AS JMLPST
	FROM
		tl_individu_standard st
	WHERE
		st.POLICYNO = tl.POLICYNO
		AND st.BULAN = tl.TEMP_BULAN
		AND st.TAHUN = tl.TEMP_TAHUN
		AND st.ID_CHILD = tl.ID_CHILD
		AND st.IDDIVISION = tl.IDDIVISION
		AND st.IDSUB = tl.IDSUB
		AND st.STATUS = 1) AS JMLPESERTA_PERDIVISI,
	(
	SELECT
		COUNT(non.TAHUN) AS COUNTED
	FROM
		tl_individu_standard non
	WHERE
		non.POLICYNO = tl.POLICYNO
		AND non.BULAN = tl.TEMP_BULAN
		AND non.TAHUN = tl.TEMP_TAHUN
		AND non.ID_CHILD = tl.ID_CHILD
		AND non.STATUS = 1) AS JMLPESERTA_PUSAT,
	tl.ID,
	tl.IDDIVISION,
	tl.IDSUB,
	tl.CREATEDATE,
	tl.DUEDATE,
	tl.PAYMENTDATE,
	tl.PRINTDATE,
	tl.ID_CHILD,
	tl.TAHUN,
	tl.TEMP_TAHUN,
	tl.BULAN,
	tl.TEMP_BULAN,
	tl.PARTNERNAME,
	tl.NMDIVISION,
	tl.NMSUB,
	tl.ALAMAT,
	tl.KOTA,
	tl.NOINVOICE,
	tl.POLICYNO,
	tl.JMLPST,
	tl.JMLPREMI,
	tl.TERBILANG,
	tl.CURRENCY,
	tl.PRODUCTCODE,
	tl.PRODUCTNAME,
	tl.BANKNAME,
	tl.ACCOUNTNAME,
	tl.ACCOUNTNUMBER,
	tl.STATUS,
	tl.REV
FROM
	tl_invoice_standard tl
WHERE
	tl.ID_CHILD != 27
	AND tl.IDDIVISION IS NOT NULL
	AND tl.IDSUB IS NOT NULL